#!/bin/bash
#
# chkconfig: 35 90 12
# description: Muxd - tcp service multiplexer
#

# Get function from functions library
. /etc/init.d/functions

# Start service
start() {
        echo -n "Starting muxd:"
        /usr/bin/muxd /etc/muxd/muxd.conf /etc/muxd/muxd.magic
        ### Create the lock file ###
        touch /var/lock/subsys/muxd
        success $"muxd startup"
        echo
}

# Stop service
stop() {
        echo -n "Stopping muxd:"
        killproc muxd
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/muxd
        echo
}

# Main
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 1
esac
exit 0
